development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zoomcar_local_1  # (create database with this name in mysql)
  pool: 15
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zoomcar_test  # (create database with this name in mysql)
  pool: 5
  username: root
  password: 

